name: Build and Push Nginx Image

on:
  push:
    branches:
      - main
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print 
        shell: bash
        env: 
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        run: 
          'echo "$DOCKER_USERNAME" | base64'
         
      - name: Print 
        shell: bash
        env: 
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        run: 
          'echo "$DOCKER_TOKEN" | base64'
          
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: nginx.dockerfile
          push: true
          tags: |
            afdulfauzan/syseng:${{ github.sha }}

      - name: Push to Docker Hub
        run: docker push afdulfauzan/syseng:${{ github.sha }}
